import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_features_features_accent" AS ENUM('primary', 'blue', 'teal', 'amber', 'violet', 'rose');
  CREATE TYPE "public"."enum_pages_blocks_features_columns" AS ENUM('auto', 'two', 'three', 'four');
  CREATE TYPE "public"."enum_pages_blocks_features_card_style" AS ENUM('elevated', 'outlined', 'soft', 'minimal');
  CREATE TYPE "public"."enum_pages_blocks_features_icon_style" AS ENUM('boxed', 'circle', 'plain');
  CREATE TYPE "public"."enum_pages_blocks_features_section_background" AS ENUM('transparent', 'light', 'muted', 'dark', 'primary');
  CREATE TYPE "public"."enum_pages_blocks_features_section_spacing" AS ENUM('none', 'compact', 'standard', 'large');
  CREATE TYPE "public"."enum_pages_blocks_features_section_content_width" AS ENUM('compact', 'standard', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_features_section_decoration" AS ENUM('none', 'glow', 'grid');
  CREATE TYPE "public"."enum_pages_blocks_stats_stats_icon" AS ENUM('none', 'calendar', 'globe', 'package', 'users', 'award', 'shield', 'truck');
  CREATE TYPE "public"."enum_pages_blocks_stats_layout_mode" AS ENUM('cards', 'band', 'minimal');
  CREATE TYPE "public"."enum_pages_blocks_stats_columns" AS ENUM('auto', 'two', 'three', 'four');
  CREATE TYPE "public"."enum_pages_blocks_stats_alignment" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum_pages_blocks_stats_section_background" AS ENUM('transparent', 'light', 'muted', 'dark', 'primary');
  CREATE TYPE "public"."enum_pages_blocks_stats_section_spacing" AS ENUM('none', 'compact', 'standard', 'large');
  CREATE TYPE "public"."enum_pages_blocks_stats_section_content_width" AS ENUM('compact', 'standard', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_stats_section_decoration" AS ENUM('none', 'glow', 'grid');
  CREATE TYPE "public"."enum_pages_blocks_gallery_image_ratio" AS ENUM('auto', 'landscape', 'wide', 'square', 'portrait');
  CREATE TYPE "public"."enum_pages_blocks_gallery_alignment" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_gallery_section_background" AS ENUM('transparent', 'light', 'muted', 'dark', 'primary');
  CREATE TYPE "public"."enum_pages_blocks_gallery_section_spacing" AS ENUM('none', 'compact', 'standard', 'large');
  CREATE TYPE "public"."enum_pages_blocks_gallery_section_content_width" AS ENUM('compact', 'standard', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_gallery_section_decoration" AS ENUM('none', 'glow', 'grid');
  CREATE TYPE "public"."enum_pages_blocks_process_steps_icon" AS ENUM('none', 'search', 'message', 'settings', 'package', 'wrench', 'truck', 'check', 'headset');
  CREATE TYPE "public"."enum_pages_blocks_process_layout_mode" AS ENUM('horizontal', 'timeline', 'cards');
  CREATE TYPE "public"."enum_pages_blocks_process_alignment" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum_pages_blocks_process_connector_style" AS ENUM('arrows', 'line', 'none');
  CREATE TYPE "public"."enum_pages_blocks_process_section_background" AS ENUM('transparent', 'light', 'muted', 'dark', 'primary');
  CREATE TYPE "public"."enum_pages_blocks_process_section_spacing" AS ENUM('none', 'compact', 'standard', 'large');
  CREATE TYPE "public"."enum_pages_blocks_process_section_content_width" AS ENUM('compact', 'standard', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_process_section_decoration" AS ENUM('none', 'glow', 'grid');
  CREATE TYPE "public"."enum__pages_v_blocks_features_features_accent" AS ENUM('primary', 'blue', 'teal', 'amber', 'violet', 'rose');
  CREATE TYPE "public"."enum__pages_v_blocks_features_columns" AS ENUM('auto', 'two', 'three', 'four');
  CREATE TYPE "public"."enum__pages_v_blocks_features_card_style" AS ENUM('elevated', 'outlined', 'soft', 'minimal');
  CREATE TYPE "public"."enum__pages_v_blocks_features_icon_style" AS ENUM('boxed', 'circle', 'plain');
  CREATE TYPE "public"."enum__pages_v_blocks_features_section_background" AS ENUM('transparent', 'light', 'muted', 'dark', 'primary');
  CREATE TYPE "public"."enum__pages_v_blocks_features_section_spacing" AS ENUM('none', 'compact', 'standard', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_features_section_content_width" AS ENUM('compact', 'standard', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_features_section_decoration" AS ENUM('none', 'glow', 'grid');
  CREATE TYPE "public"."enum__pages_v_blocks_stats_stats_icon" AS ENUM('none', 'calendar', 'globe', 'package', 'users', 'award', 'shield', 'truck');
  CREATE TYPE "public"."enum__pages_v_blocks_stats_layout_mode" AS ENUM('cards', 'band', 'minimal');
  CREATE TYPE "public"."enum__pages_v_blocks_stats_columns" AS ENUM('auto', 'two', 'three', 'four');
  CREATE TYPE "public"."enum__pages_v_blocks_stats_alignment" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum__pages_v_blocks_stats_section_background" AS ENUM('transparent', 'light', 'muted', 'dark', 'primary');
  CREATE TYPE "public"."enum__pages_v_blocks_stats_section_spacing" AS ENUM('none', 'compact', 'standard', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_stats_section_content_width" AS ENUM('compact', 'standard', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_stats_section_decoration" AS ENUM('none', 'glow', 'grid');
  CREATE TYPE "public"."enum__pages_v_blocks_gallery_image_ratio" AS ENUM('auto', 'landscape', 'wide', 'square', 'portrait');
  CREATE TYPE "public"."enum__pages_v_blocks_gallery_alignment" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_gallery_section_background" AS ENUM('transparent', 'light', 'muted', 'dark', 'primary');
  CREATE TYPE "public"."enum__pages_v_blocks_gallery_section_spacing" AS ENUM('none', 'compact', 'standard', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_gallery_section_content_width" AS ENUM('compact', 'standard', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_gallery_section_decoration" AS ENUM('none', 'glow', 'grid');
  CREATE TYPE "public"."enum__pages_v_blocks_process_steps_icon" AS ENUM('none', 'search', 'message', 'settings', 'package', 'wrench', 'truck', 'check', 'headset');
  CREATE TYPE "public"."enum__pages_v_blocks_process_layout_mode" AS ENUM('horizontal', 'timeline', 'cards');
  CREATE TYPE "public"."enum__pages_v_blocks_process_alignment" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum__pages_v_blocks_process_connector_style" AS ENUM('arrows', 'line', 'none');
  CREATE TYPE "public"."enum__pages_v_blocks_process_section_background" AS ENUM('transparent', 'light', 'muted', 'dark', 'primary');
  CREATE TYPE "public"."enum__pages_v_blocks_process_section_spacing" AS ENUM('none', 'compact', 'standard', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_process_section_content_width" AS ENUM('compact', 'standard', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_process_section_decoration" AS ENUM('none', 'glow', 'grid');
  ALTER TYPE "public"."enum_pages_blocks_features_features_icon" ADD VALUE 'check';
  ALTER TYPE "public"."enum_pages_blocks_features_features_icon" ADD VALUE 'award';
  ALTER TYPE "public"."enum_pages_blocks_features_features_icon" ADD VALUE 'wrench';
  ALTER TYPE "public"."enum_pages_blocks_features_features_icon" ADD VALUE 'package';
  ALTER TYPE "public"."enum_pages_blocks_features_features_icon" ADD VALUE 'truck';
  ALTER TYPE "public"."enum_pages_blocks_features_features_icon" ADD VALUE 'headset';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_icon" ADD VALUE 'check';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_icon" ADD VALUE 'award';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_icon" ADD VALUE 'wrench';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_icon" ADD VALUE 'package';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_icon" ADD VALUE 'truck';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_icon" ADD VALUE 'headset';
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "icon" SET DEFAULT 'star';
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "icon" SET DEFAULT 'star';
  ALTER TABLE "pages_blocks_features_features" ADD COLUMN "accent" "enum_pages_blocks_features_features_accent" DEFAULT 'primary';
  ALTER TABLE "pages_blocks_features_features" ADD COLUMN "image_id" integer;
  ALTER TABLE "pages_blocks_features_features" ADD COLUMN "link_text" varchar;
  ALTER TABLE "pages_blocks_features_features" ADD COLUMN "link" varchar;
  ALTER TABLE "pages_blocks_features" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "pages_blocks_features" ADD COLUMN "columns" "enum_pages_blocks_features_columns" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_features" ADD COLUMN "card_style" "enum_pages_blocks_features_card_style" DEFAULT 'elevated';
  ALTER TABLE "pages_blocks_features" ADD COLUMN "icon_style" "enum_pages_blocks_features_icon_style" DEFAULT 'boxed';
  ALTER TABLE "pages_blocks_features" ADD COLUMN "section_anchor" varchar;
  ALTER TABLE "pages_blocks_features" ADD COLUMN "section_background" "enum_pages_blocks_features_section_background" DEFAULT 'muted';
  ALTER TABLE "pages_blocks_features" ADD COLUMN "section_spacing" "enum_pages_blocks_features_section_spacing" DEFAULT 'standard';
  ALTER TABLE "pages_blocks_features" ADD COLUMN "section_content_width" "enum_pages_blocks_features_section_content_width" DEFAULT 'wide';
  ALTER TABLE "pages_blocks_features" ADD COLUMN "section_divider_top" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_features" ADD COLUMN "section_divider_bottom" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_features" ADD COLUMN "section_decoration" "enum_pages_blocks_features_section_decoration" DEFAULT 'none';
  ALTER TABLE "pages_blocks_stats_stats" ADD COLUMN "icon" "enum_pages_blocks_stats_stats_icon";
  ALTER TABLE "pages_blocks_stats_stats" ADD COLUMN "prefix" varchar;
  ALTER TABLE "pages_blocks_stats_stats" ADD COLUMN "suffix" varchar;
  ALTER TABLE "pages_blocks_stats_stats" ADD COLUMN "note" varchar;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "title" varchar;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "subtitle" varchar;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "layout_mode" "enum_pages_blocks_stats_layout_mode" DEFAULT 'cards';
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "columns" "enum_pages_blocks_stats_columns" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "alignment" "enum_pages_blocks_stats_alignment" DEFAULT 'center';
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "animate_values" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "show_dividers" boolean DEFAULT true;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "section_anchor" varchar;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "section_background" "enum_pages_blocks_stats_section_background" DEFAULT 'primary';
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "section_spacing" "enum_pages_blocks_stats_section_spacing" DEFAULT 'compact';
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "section_content_width" "enum_pages_blocks_stats_section_content_width" DEFAULT 'wide';
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "section_divider_top" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "section_divider_bottom" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "section_decoration" "enum_pages_blocks_stats_section_decoration" DEFAULT 'none';
  ALTER TABLE "pages_blocks_gallery_images" ADD COLUMN "title" varchar;
  ALTER TABLE "pages_blocks_gallery_images" ADD COLUMN "description" varchar;
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "subtitle" varchar;
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "image_ratio" "enum_pages_blocks_gallery_image_ratio" DEFAULT 'landscape';
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "alignment" "enum_pages_blocks_gallery_alignment" DEFAULT 'left';
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "enable_lightbox" boolean DEFAULT true;
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "show_captions" boolean DEFAULT true;
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "section_anchor" varchar;
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "section_background" "enum_pages_blocks_gallery_section_background" DEFAULT 'muted';
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "section_spacing" "enum_pages_blocks_gallery_section_spacing" DEFAULT 'large';
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "section_content_width" "enum_pages_blocks_gallery_section_content_width" DEFAULT 'wide';
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "section_divider_top" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "section_divider_bottom" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "section_decoration" "enum_pages_blocks_gallery_section_decoration" DEFAULT 'none';
  ALTER TABLE "pages_blocks_process_steps" ADD COLUMN "icon" "enum_pages_blocks_process_steps_icon";
  ALTER TABLE "pages_blocks_process_steps" ADD COLUMN "image_id" integer;
  ALTER TABLE "pages_blocks_process_steps" ADD COLUMN "link_text" varchar;
  ALTER TABLE "pages_blocks_process_steps" ADD COLUMN "link" varchar;
  ALTER TABLE "pages_blocks_process" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "pages_blocks_process" ADD COLUMN "subtitle" varchar;
  ALTER TABLE "pages_blocks_process" ADD COLUMN "layout_mode" "enum_pages_blocks_process_layout_mode" DEFAULT 'horizontal';
  ALTER TABLE "pages_blocks_process" ADD COLUMN "alignment" "enum_pages_blocks_process_alignment" DEFAULT 'center';
  ALTER TABLE "pages_blocks_process" ADD COLUMN "connector_style" "enum_pages_blocks_process_connector_style" DEFAULT 'arrows';
  ALTER TABLE "pages_blocks_process" ADD COLUMN "animate_connectors" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_process" ADD COLUMN "section_anchor" varchar;
  ALTER TABLE "pages_blocks_process" ADD COLUMN "section_background" "enum_pages_blocks_process_section_background" DEFAULT 'light';
  ALTER TABLE "pages_blocks_process" ADD COLUMN "section_spacing" "enum_pages_blocks_process_section_spacing" DEFAULT 'large';
  ALTER TABLE "pages_blocks_process" ADD COLUMN "section_content_width" "enum_pages_blocks_process_section_content_width" DEFAULT 'wide';
  ALTER TABLE "pages_blocks_process" ADD COLUMN "section_divider_top" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_process" ADD COLUMN "section_divider_bottom" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_process" ADD COLUMN "section_decoration" "enum_pages_blocks_process_section_decoration" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_features_features" ADD COLUMN "accent" "enum__pages_v_blocks_features_features_accent" DEFAULT 'primary';
  ALTER TABLE "_pages_v_blocks_features_features" ADD COLUMN "image_id" integer;
  ALTER TABLE "_pages_v_blocks_features_features" ADD COLUMN "link_text" varchar;
  ALTER TABLE "_pages_v_blocks_features_features" ADD COLUMN "link" varchar;
  ALTER TABLE "_pages_v_blocks_features" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "_pages_v_blocks_features" ADD COLUMN "columns" "enum__pages_v_blocks_features_columns" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_features" ADD COLUMN "card_style" "enum__pages_v_blocks_features_card_style" DEFAULT 'elevated';
  ALTER TABLE "_pages_v_blocks_features" ADD COLUMN "icon_style" "enum__pages_v_blocks_features_icon_style" DEFAULT 'boxed';
  ALTER TABLE "_pages_v_blocks_features" ADD COLUMN "section_anchor" varchar;
  ALTER TABLE "_pages_v_blocks_features" ADD COLUMN "section_background" "enum__pages_v_blocks_features_section_background" DEFAULT 'muted';
  ALTER TABLE "_pages_v_blocks_features" ADD COLUMN "section_spacing" "enum__pages_v_blocks_features_section_spacing" DEFAULT 'standard';
  ALTER TABLE "_pages_v_blocks_features" ADD COLUMN "section_content_width" "enum__pages_v_blocks_features_section_content_width" DEFAULT 'wide';
  ALTER TABLE "_pages_v_blocks_features" ADD COLUMN "section_divider_top" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_features" ADD COLUMN "section_divider_bottom" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_features" ADD COLUMN "section_decoration" "enum__pages_v_blocks_features_section_decoration" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_stats_stats" ADD COLUMN "icon" "enum__pages_v_blocks_stats_stats_icon";
  ALTER TABLE "_pages_v_blocks_stats_stats" ADD COLUMN "prefix" varchar;
  ALTER TABLE "_pages_v_blocks_stats_stats" ADD COLUMN "suffix" varchar;
  ALTER TABLE "_pages_v_blocks_stats_stats" ADD COLUMN "note" varchar;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "title" varchar;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "subtitle" varchar;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "layout_mode" "enum__pages_v_blocks_stats_layout_mode" DEFAULT 'cards';
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "columns" "enum__pages_v_blocks_stats_columns" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "alignment" "enum__pages_v_blocks_stats_alignment" DEFAULT 'center';
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "animate_values" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "show_dividers" boolean DEFAULT true;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "section_anchor" varchar;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "section_background" "enum__pages_v_blocks_stats_section_background" DEFAULT 'primary';
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "section_spacing" "enum__pages_v_blocks_stats_section_spacing" DEFAULT 'compact';
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "section_content_width" "enum__pages_v_blocks_stats_section_content_width" DEFAULT 'wide';
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "section_divider_top" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "section_divider_bottom" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "section_decoration" "enum__pages_v_blocks_stats_section_decoration" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_gallery_images" ADD COLUMN "title" varchar;
  ALTER TABLE "_pages_v_blocks_gallery_images" ADD COLUMN "description" varchar;
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "subtitle" varchar;
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "image_ratio" "enum__pages_v_blocks_gallery_image_ratio" DEFAULT 'landscape';
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "alignment" "enum__pages_v_blocks_gallery_alignment" DEFAULT 'left';
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "enable_lightbox" boolean DEFAULT true;
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "show_captions" boolean DEFAULT true;
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "section_anchor" varchar;
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "section_background" "enum__pages_v_blocks_gallery_section_background" DEFAULT 'muted';
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "section_spacing" "enum__pages_v_blocks_gallery_section_spacing" DEFAULT 'large';
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "section_content_width" "enum__pages_v_blocks_gallery_section_content_width" DEFAULT 'wide';
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "section_divider_top" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "section_divider_bottom" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "section_decoration" "enum__pages_v_blocks_gallery_section_decoration" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_process_steps" ADD COLUMN "icon" "enum__pages_v_blocks_process_steps_icon";
  ALTER TABLE "_pages_v_blocks_process_steps" ADD COLUMN "image_id" integer;
  ALTER TABLE "_pages_v_blocks_process_steps" ADD COLUMN "link_text" varchar;
  ALTER TABLE "_pages_v_blocks_process_steps" ADD COLUMN "link" varchar;
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "subtitle" varchar;
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "layout_mode" "enum__pages_v_blocks_process_layout_mode" DEFAULT 'horizontal';
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "alignment" "enum__pages_v_blocks_process_alignment" DEFAULT 'center';
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "connector_style" "enum__pages_v_blocks_process_connector_style" DEFAULT 'arrows';
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "animate_connectors" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "section_anchor" varchar;
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "section_background" "enum__pages_v_blocks_process_section_background" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "section_spacing" "enum__pages_v_blocks_process_section_spacing" DEFAULT 'large';
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "section_content_width" "enum__pages_v_blocks_process_section_content_width" DEFAULT 'wide';
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "section_divider_top" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "section_divider_bottom" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "section_decoration" "enum__pages_v_blocks_process_section_decoration" DEFAULT 'none';
  ALTER TABLE "pages_blocks_features_features" ADD CONSTRAINT "pages_blocks_features_features_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_process_steps" ADD CONSTRAINT "pages_blocks_process_steps_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_features_features" ADD CONSTRAINT "_pages_v_blocks_features_features_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_process_steps" ADD CONSTRAINT "_pages_v_blocks_process_steps_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "pages_blocks_features_features_image_idx" ON "pages_blocks_features_features" USING btree ("image_id");
  CREATE INDEX "pages_blocks_process_steps_image_idx" ON "pages_blocks_process_steps" USING btree ("image_id");
  CREATE INDEX "_pages_v_blocks_features_features_image_idx" ON "_pages_v_blocks_features_features" USING btree ("image_id");
  CREATE INDEX "_pages_v_blocks_process_steps_image_idx" ON "_pages_v_blocks_process_steps" USING btree ("image_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_features_features" DROP CONSTRAINT "pages_blocks_features_features_image_id_media_id_fk";
  
  ALTER TABLE "pages_blocks_process_steps" DROP CONSTRAINT "pages_blocks_process_steps_image_id_media_id_fk";
  
  ALTER TABLE "_pages_v_blocks_features_features" DROP CONSTRAINT "_pages_v_blocks_features_features_image_id_media_id_fk";
  
  ALTER TABLE "_pages_v_blocks_process_steps" DROP CONSTRAINT "_pages_v_blocks_process_steps_image_id_media_id_fk";
  
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_features_features_icon";
  CREATE TYPE "public"."enum_pages_blocks_features_features_icon" AS ENUM('star', 'shield', 'cpu', 'globe', 'heart', 'settings');
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_pages_blocks_features_features_icon" USING "icon"::"public"."enum_pages_blocks_features_features_icon";
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_features_features_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_features_features_icon" AS ENUM('star', 'shield', 'cpu', 'globe', 'heart', 'settings');
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__pages_v_blocks_features_features_icon" USING "icon"::"public"."enum__pages_v_blocks_features_features_icon";
  DROP INDEX "pages_blocks_features_features_image_idx";
  DROP INDEX "pages_blocks_process_steps_image_idx";
  DROP INDEX "_pages_v_blocks_features_features_image_idx";
  DROP INDEX "_pages_v_blocks_process_steps_image_idx";
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "icon" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "icon" DROP DEFAULT;
  ALTER TABLE "pages_blocks_features_features" DROP COLUMN "accent";
  ALTER TABLE "pages_blocks_features_features" DROP COLUMN "image_id";
  ALTER TABLE "pages_blocks_features_features" DROP COLUMN "link_text";
  ALTER TABLE "pages_blocks_features_features" DROP COLUMN "link";
  ALTER TABLE "pages_blocks_features" DROP COLUMN "eyebrow";
  ALTER TABLE "pages_blocks_features" DROP COLUMN "columns";
  ALTER TABLE "pages_blocks_features" DROP COLUMN "card_style";
  ALTER TABLE "pages_blocks_features" DROP COLUMN "icon_style";
  ALTER TABLE "pages_blocks_features" DROP COLUMN "section_anchor";
  ALTER TABLE "pages_blocks_features" DROP COLUMN "section_background";
  ALTER TABLE "pages_blocks_features" DROP COLUMN "section_spacing";
  ALTER TABLE "pages_blocks_features" DROP COLUMN "section_content_width";
  ALTER TABLE "pages_blocks_features" DROP COLUMN "section_divider_top";
  ALTER TABLE "pages_blocks_features" DROP COLUMN "section_divider_bottom";
  ALTER TABLE "pages_blocks_features" DROP COLUMN "section_decoration";
  ALTER TABLE "pages_blocks_stats_stats" DROP COLUMN "icon";
  ALTER TABLE "pages_blocks_stats_stats" DROP COLUMN "prefix";
  ALTER TABLE "pages_blocks_stats_stats" DROP COLUMN "suffix";
  ALTER TABLE "pages_blocks_stats_stats" DROP COLUMN "note";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "eyebrow";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "title";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "subtitle";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "layout_mode";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "columns";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "alignment";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "animate_values";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "show_dividers";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "section_anchor";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "section_background";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "section_spacing";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "section_content_width";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "section_divider_top";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "section_divider_bottom";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "section_decoration";
  ALTER TABLE "pages_blocks_gallery_images" DROP COLUMN "title";
  ALTER TABLE "pages_blocks_gallery_images" DROP COLUMN "description";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "eyebrow";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "subtitle";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "image_ratio";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "alignment";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "enable_lightbox";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "show_captions";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "section_anchor";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "section_background";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "section_spacing";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "section_content_width";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "section_divider_top";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "section_divider_bottom";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "section_decoration";
  ALTER TABLE "pages_blocks_process_steps" DROP COLUMN "icon";
  ALTER TABLE "pages_blocks_process_steps" DROP COLUMN "image_id";
  ALTER TABLE "pages_blocks_process_steps" DROP COLUMN "link_text";
  ALTER TABLE "pages_blocks_process_steps" DROP COLUMN "link";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "eyebrow";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "subtitle";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "layout_mode";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "alignment";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "connector_style";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "animate_connectors";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "section_anchor";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "section_background";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "section_spacing";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "section_content_width";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "section_divider_top";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "section_divider_bottom";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "section_decoration";
  ALTER TABLE "_pages_v_blocks_features_features" DROP COLUMN "accent";
  ALTER TABLE "_pages_v_blocks_features_features" DROP COLUMN "image_id";
  ALTER TABLE "_pages_v_blocks_features_features" DROP COLUMN "link_text";
  ALTER TABLE "_pages_v_blocks_features_features" DROP COLUMN "link";
  ALTER TABLE "_pages_v_blocks_features" DROP COLUMN "eyebrow";
  ALTER TABLE "_pages_v_blocks_features" DROP COLUMN "columns";
  ALTER TABLE "_pages_v_blocks_features" DROP COLUMN "card_style";
  ALTER TABLE "_pages_v_blocks_features" DROP COLUMN "icon_style";
  ALTER TABLE "_pages_v_blocks_features" DROP COLUMN "section_anchor";
  ALTER TABLE "_pages_v_blocks_features" DROP COLUMN "section_background";
  ALTER TABLE "_pages_v_blocks_features" DROP COLUMN "section_spacing";
  ALTER TABLE "_pages_v_blocks_features" DROP COLUMN "section_content_width";
  ALTER TABLE "_pages_v_blocks_features" DROP COLUMN "section_divider_top";
  ALTER TABLE "_pages_v_blocks_features" DROP COLUMN "section_divider_bottom";
  ALTER TABLE "_pages_v_blocks_features" DROP COLUMN "section_decoration";
  ALTER TABLE "_pages_v_blocks_stats_stats" DROP COLUMN "icon";
  ALTER TABLE "_pages_v_blocks_stats_stats" DROP COLUMN "prefix";
  ALTER TABLE "_pages_v_blocks_stats_stats" DROP COLUMN "suffix";
  ALTER TABLE "_pages_v_blocks_stats_stats" DROP COLUMN "note";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "eyebrow";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "title";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "subtitle";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "layout_mode";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "columns";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "alignment";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "animate_values";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "show_dividers";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "section_anchor";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "section_background";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "section_spacing";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "section_content_width";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "section_divider_top";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "section_divider_bottom";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "section_decoration";
  ALTER TABLE "_pages_v_blocks_gallery_images" DROP COLUMN "title";
  ALTER TABLE "_pages_v_blocks_gallery_images" DROP COLUMN "description";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "eyebrow";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "subtitle";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "image_ratio";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "alignment";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "enable_lightbox";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "show_captions";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "section_anchor";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "section_background";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "section_spacing";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "section_content_width";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "section_divider_top";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "section_divider_bottom";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "section_decoration";
  ALTER TABLE "_pages_v_blocks_process_steps" DROP COLUMN "icon";
  ALTER TABLE "_pages_v_blocks_process_steps" DROP COLUMN "image_id";
  ALTER TABLE "_pages_v_blocks_process_steps" DROP COLUMN "link_text";
  ALTER TABLE "_pages_v_blocks_process_steps" DROP COLUMN "link";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "eyebrow";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "subtitle";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "layout_mode";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "alignment";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "connector_style";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "animate_connectors";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "section_anchor";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "section_background";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "section_spacing";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "section_content_width";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "section_divider_top";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "section_divider_bottom";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "section_decoration";
  DROP TYPE "public"."enum_pages_blocks_features_features_accent";
  DROP TYPE "public"."enum_pages_blocks_features_columns";
  DROP TYPE "public"."enum_pages_blocks_features_card_style";
  DROP TYPE "public"."enum_pages_blocks_features_icon_style";
  DROP TYPE "public"."enum_pages_blocks_features_section_background";
  DROP TYPE "public"."enum_pages_blocks_features_section_spacing";
  DROP TYPE "public"."enum_pages_blocks_features_section_content_width";
  DROP TYPE "public"."enum_pages_blocks_features_section_decoration";
  DROP TYPE "public"."enum_pages_blocks_stats_stats_icon";
  DROP TYPE "public"."enum_pages_blocks_stats_layout_mode";
  DROP TYPE "public"."enum_pages_blocks_stats_columns";
  DROP TYPE "public"."enum_pages_blocks_stats_alignment";
  DROP TYPE "public"."enum_pages_blocks_stats_section_background";
  DROP TYPE "public"."enum_pages_blocks_stats_section_spacing";
  DROP TYPE "public"."enum_pages_blocks_stats_section_content_width";
  DROP TYPE "public"."enum_pages_blocks_stats_section_decoration";
  DROP TYPE "public"."enum_pages_blocks_gallery_image_ratio";
  DROP TYPE "public"."enum_pages_blocks_gallery_alignment";
  DROP TYPE "public"."enum_pages_blocks_gallery_section_background";
  DROP TYPE "public"."enum_pages_blocks_gallery_section_spacing";
  DROP TYPE "public"."enum_pages_blocks_gallery_section_content_width";
  DROP TYPE "public"."enum_pages_blocks_gallery_section_decoration";
  DROP TYPE "public"."enum_pages_blocks_process_steps_icon";
  DROP TYPE "public"."enum_pages_blocks_process_layout_mode";
  DROP TYPE "public"."enum_pages_blocks_process_alignment";
  DROP TYPE "public"."enum_pages_blocks_process_connector_style";
  DROP TYPE "public"."enum_pages_blocks_process_section_background";
  DROP TYPE "public"."enum_pages_blocks_process_section_spacing";
  DROP TYPE "public"."enum_pages_blocks_process_section_content_width";
  DROP TYPE "public"."enum_pages_blocks_process_section_decoration";
  DROP TYPE "public"."enum__pages_v_blocks_features_features_accent";
  DROP TYPE "public"."enum__pages_v_blocks_features_columns";
  DROP TYPE "public"."enum__pages_v_blocks_features_card_style";
  DROP TYPE "public"."enum__pages_v_blocks_features_icon_style";
  DROP TYPE "public"."enum__pages_v_blocks_features_section_background";
  DROP TYPE "public"."enum__pages_v_blocks_features_section_spacing";
  DROP TYPE "public"."enum__pages_v_blocks_features_section_content_width";
  DROP TYPE "public"."enum__pages_v_blocks_features_section_decoration";
  DROP TYPE "public"."enum__pages_v_blocks_stats_stats_icon";
  DROP TYPE "public"."enum__pages_v_blocks_stats_layout_mode";
  DROP TYPE "public"."enum__pages_v_blocks_stats_columns";
  DROP TYPE "public"."enum__pages_v_blocks_stats_alignment";
  DROP TYPE "public"."enum__pages_v_blocks_stats_section_background";
  DROP TYPE "public"."enum__pages_v_blocks_stats_section_spacing";
  DROP TYPE "public"."enum__pages_v_blocks_stats_section_content_width";
  DROP TYPE "public"."enum__pages_v_blocks_stats_section_decoration";
  DROP TYPE "public"."enum__pages_v_blocks_gallery_image_ratio";
  DROP TYPE "public"."enum__pages_v_blocks_gallery_alignment";
  DROP TYPE "public"."enum__pages_v_blocks_gallery_section_background";
  DROP TYPE "public"."enum__pages_v_blocks_gallery_section_spacing";
  DROP TYPE "public"."enum__pages_v_blocks_gallery_section_content_width";
  DROP TYPE "public"."enum__pages_v_blocks_gallery_section_decoration";
  DROP TYPE "public"."enum__pages_v_blocks_process_steps_icon";
  DROP TYPE "public"."enum__pages_v_blocks_process_layout_mode";
  DROP TYPE "public"."enum__pages_v_blocks_process_alignment";
  DROP TYPE "public"."enum__pages_v_blocks_process_connector_style";
  DROP TYPE "public"."enum__pages_v_blocks_process_section_background";
  DROP TYPE "public"."enum__pages_v_blocks_process_section_spacing";
  DROP TYPE "public"."enum__pages_v_blocks_process_section_content_width";
  DROP TYPE "public"."enum__pages_v_blocks_process_section_decoration";`)
}
