/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    categories: Category;
    inquiries: Inquiry;
    news: News;
    pages: Page;
    'news-categories': NewsCategory;
    'quote-requests': QuoteRequest;
    'download-logs': DownloadLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'news-categories': NewsCategoriesSelect<false> | NewsCategoriesSelect<true>;
    'quote-requests': QuoteRequestsSelect<false> | QuoteRequestsSelect<true>;
    'download-logs': DownloadLogsSelect<false> | DownloadLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'main-menu': MainMenu;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'main-menu': MainMenuSelect<false> | MainMenuSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  firstName?: string | null;
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Görseller için SEO metni, PDF'ler için dosya başlığı olarak kullanılır.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  shortDescription?: string | null;
  /**
   * Buraya Markdown (## Başlık, | Tablo |) veya doğrudan HTML (<p><strong>...</strong></p>) yapıştırabilirsiniz.
   */
  description?: string | null;
  specs?:
    | {
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  mainImage: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  videoUrl?: string | null;
  skuPrefix?: string | null;
  skuSuffix?: string | null;
  /**
   * Değerleri TİRE (-) ile ayırarak yazın. Örn: 0.6-0.65-0.7
   */
  attributes?:
    | {
        name: string;
        values: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Bunu işaretleyip kaydettiğinizde, yukarıdaki özelliklerin tüm kombinasyonları hesaplanır, özel kurallara göre SKU kodları oluşturulur ve aşağıdaki listeye otomatik eklenir.
   */
  triggerVariantGeneration?: boolean | null;
  /**
   * Bu liste otomatik dolar ancak sonrasında manuel müdahale edip istisnai durumları düzeltebilirsiniz.
   */
  variants?:
    | {
        title: string;
        sku: string;
        price?: string | null;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Teknik ve lojistik verilerin ürün sayfasındaki konumunu belirler.
   */
  logisticDisplayPosition?: ('below' | 'sidebar' | 'both') | null;
  width?: string | null;
  height?: string | null;
  depth?: string | null;
  weight?: string | null;
  /**
   * Ürünün farklı paketleme formlarını (Örn: Tekli Kutu, 50’li Ana Koli) buraya ekleyebilirsiniz.
   */
  packaging?:
    | {
        packageLabel: string;
        quantity?: number | null;
        grossWeight?: string | null;
        p_width?: string | null;
        p_height?: string | null;
        p_depth?: string | null;
        id?: string | null;
      }[]
    | null;
  publicDocs?:
    | {
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  protectedDocs?:
    | {
        label: string;
        file: number | Media;
        accessCodes?:
          | {
              code: string;
              isActive?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Bu içeriğin Google, WhatsApp, LinkedIn gibi platformlarda nasıl görüneceğini belirleyin.
   */
  meta?: {
    /**
     * Boş bırakılırsa içeriğin ana başlığı kullanılır. (Önerilen: 50-60 karakter)
     */
    title?: string | null;
    /**
     * Arama sonuçlarında başlığın altında görünecek özet metin. (Önerilen: 150-160 karakter)
     */
    description?: string | null;
    /**
     * Link paylaşıldığında görünecek özel kapak fotoğrafı. 1200x630 piksel önerilir. Boş bırakılırsa ana görsel kullanılır.
     */
    image?: (number | null) | Media;
    /**
     * Kelimelerin arasına virgül koyarak yazın. (Örn: medikal cihaz, saç ekimi, fue)
     */
    keywords?: string | null;
  };
  sku?: string | null;
  category: (number | Category)[];
  relatedProducts?: (number | Product)[] | null;
  isFeatured?: boolean | null;
  /**
   * Otomatik oluşturulur. Gerekirse manuel olarak düzenleyebilirsiniz.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  parent?: (number | null) | Category;
  description?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  status?: ('unread' | 'pending' | 'resolved') | null;
  name: string;
  email: string;
  phone?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Bu içeriğin Google, WhatsApp, LinkedIn gibi platformlarda nasıl görüneceğini belirleyin.
   */
  meta?: {
    /**
     * Boş bırakılırsa içeriğin ana başlığı kullanılır. (Önerilen: 50-60 karakter)
     */
    title?: string | null;
    /**
     * Arama sonuçlarında başlığın altında görünecek özet metin. (Önerilen: 150-160 karakter)
     */
    description?: string | null;
    /**
     * Link paylaşıldığında görünecek özel kapak fotoğrafı. 1200x630 piksel önerilir. Boş bırakılırsa ana görsel kullanılır.
     */
    image?: (number | null) | Media;
    /**
     * Kelimelerin arasına virgül koyarak yazın. (Örn: medikal cihaz, saç ekimi, fue)
     */
    keywords?: string | null;
  };
  category?: (number | null) | NewsCategory;
  publishedDate: string;
  /**
   * Otomatik oluşturulur. Gerekirse manuel olarak düzenleyebilirsiniz.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories".
 */
export interface NewsCategory {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            backgroundImage?: (number | null) | Media;
            buttons?:
              | {
                  label: string;
                  link: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            features?:
              | {
                  icon?: ('star' | 'shield' | 'cpu' | 'globe' | 'heart' | 'settings') | null;
                  featureTitle: string;
                  featureDescription?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            title?: string | null;
            selectionType?: ('featured' | 'latest' | 'manual') | null;
            selectedProducts?: (number | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredProducts';
          }
        | {
            title?: string | null;
            questions?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            title?: string | null;
            testimonials?:
              | {
                  name: string;
                  content: string;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonial';
          }
        | {
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            title?: string | null;
            images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            title?: string | null;
            logos?:
              | {
                  logo: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoSlider';
          }
        | {
            title?: string | null;
            address: string;
            phone?: string | null;
            email?: string | null;
            workingHours?: string | null;
            /**
             * Google Haritalar -> Paylaş -> Harita Yerleştirme (Embed) kısmındaki src="" içindeki linki buraya yapıştırın.
             */
            mapUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'location';
          }
        | {
            title?: string | null;
            members?:
              | {
                  name: string;
                  role: string;
                  image?: (number | null) | Media;
                  linkedin?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            title?: string | null;
            description?: string | null;
            buttonText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            slides?:
              | {
                  image?: (number | null) | Media;
                  title: string;
                  subtitle?: string | null;
                  buttonText?: string | null;
                  buttonLink?: string | null;
                  overlayOpacity?: ('0.2' | '0.4' | '0.6') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSlider';
          }
        | {
            title?: string | null;
            certificates?:
              | {
                  image: number | Media;
                  name: string;
                  issuer?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'certificateGrid';
          }
        | {
            title?: string | null;
            showArrows?: boolean | null;
            steps?:
              | {
                  stepNumber: string;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'process';
          }
        | {
            title: string;
            description?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            theme?: ('primary' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  /**
   * Bu içeriğin Google, WhatsApp, LinkedIn gibi platformlarda nasıl görüneceğini belirleyin.
   */
  meta?: {
    /**
     * Boş bırakılırsa içeriğin ana başlığı kullanılır. (Önerilen: 50-60 karakter)
     */
    title?: string | null;
    /**
     * Arama sonuçlarında başlığın altında görünecek özet metin. (Önerilen: 150-160 karakter)
     */
    description?: string | null;
    /**
     * Link paylaşıldığında görünecek özel kapak fotoğrafı. 1200x630 piksel önerilir. Boş bırakılırsa ana görsel kullanılır.
     */
    image?: (number | null) | Media;
    /**
     * Kelimelerin arasına virgül koyarak yazın. (Örn: medikal cihaz, saç ekimi, fue)
     */
    keywords?: string | null;
  };
  /**
   * Otomatik oluşturulur. Gerekirse manuel olarak düzenleyebilirsiniz.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests".
 */
export interface QuoteRequest {
  id: number;
  customerName: string;
  company?: string | null;
  email: string;
  phone: string;
  message?: string | null;
  status?: ('new' | 'reviewing' | 'quoted' | 'closed') | null;
  items: {
    productTitle?: string | null;
    variantInfo?: string | null;
    sku?: string | null;
    quantity?: number | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download-logs".
 */
export interface DownloadLog {
  id: number;
  productTitle?: string | null;
  documentName?: string | null;
  accessCode?: string | null;
  ipAddress?: string | null;
  country?: string | null;
  deviceInfo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news-categories';
        value: number | NewsCategory;
      } | null)
    | ({
        relationTo: 'quote-requests';
        value: number | QuoteRequest;
      } | null)
    | ({
        relationTo: 'download-logs';
        value: number | DownloadLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  description?: T;
  specs?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  mainImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  videoUrl?: T;
  skuPrefix?: T;
  skuSuffix?: T;
  attributes?:
    | T
    | {
        name?: T;
        values?: T;
        id?: T;
      };
  triggerVariantGeneration?: T;
  variants?:
    | T
    | {
        title?: T;
        sku?: T;
        price?: T;
        isActive?: T;
        id?: T;
      };
  logisticDisplayPosition?: T;
  width?: T;
  height?: T;
  depth?: T;
  weight?: T;
  packaging?:
    | T
    | {
        packageLabel?: T;
        quantity?: T;
        grossWeight?: T;
        p_width?: T;
        p_height?: T;
        p_depth?: T;
        id?: T;
      };
  publicDocs?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  protectedDocs?:
    | T
    | {
        label?: T;
        file?: T;
        accessCodes?:
          | T
          | {
              code?: T;
              isActive?: T;
              id?: T;
            };
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
      };
  sku?: T;
  category?: T;
  relatedProducts?: T;
  isFeatured?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
      };
  category?: T;
  publishedDate?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              title?: T;
              subtitle?: T;
              features?:
                | T
                | {
                    icon?: T;
                    featureTitle?: T;
                    featureDescription?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featuredProducts?:
          | T
          | {
              title?: T;
              selectionType?: T;
              selectedProducts?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              questions?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonial?:
          | T
          | {
              title?: T;
              testimonials?:
                | T
                | {
                    name?: T;
                    content?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoSlider?:
          | T
          | {
              title?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        location?:
          | T
          | {
              title?: T;
              address?: T;
              phone?: T;
              email?: T;
              workingHours?: T;
              mapUrl?: T;
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              title?: T;
              members?:
                | T
                | {
                    name?: T;
                    role?: T;
                    image?: T;
                    linkedin?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              id?: T;
              blockName?: T;
            };
        heroSlider?:
          | T
          | {
              slides?:
                | T
                | {
                    image?: T;
                    title?: T;
                    subtitle?: T;
                    buttonText?: T;
                    buttonLink?: T;
                    overlayOpacity?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        certificateGrid?:
          | T
          | {
              title?: T;
              certificates?:
                | T
                | {
                    image?: T;
                    name?: T;
                    issuer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              title?: T;
              showArrows?: T;
              steps?:
                | T
                | {
                    stepNumber?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories_select".
 */
export interface NewsCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests_select".
 */
export interface QuoteRequestsSelect<T extends boolean = true> {
  customerName?: T;
  company?: T;
  email?: T;
  phone?: T;
  message?: T;
  status?: T;
  items?:
    | T
    | {
        productTitle?: T;
        variantInfo?: T;
        sku?: T;
        quantity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download-logs_select".
 */
export interface DownloadLogsSelect<T extends boolean = true> {
  productTitle?: T;
  documentName?: T;
  accessCode?: T;
  ipAddress?: T;
  country?: T;
  deviceInfo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  general: {
    siteLogo: number | Media;
    whiteLogo?: (number | null) | Media;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  socialMedia?:
    | {
        platform?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  footer?: {
    columns?:
      | (
          | {
              showLogo?: boolean | null;
              text?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'textColumn';
            }
          | {
              title: string;
              links?:
                | {
                    label: string;
                    url: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'menuColumn';
            }
          | {
              title?: string | null;
              showAddress?: boolean | null;
              showPhone?: boolean | null;
              showEmail?: boolean | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'contactColumn';
            }
        )[]
      | null;
    bottomLinks?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
    copyright?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu".
 */
export interface MainMenu {
  id: number;
  items?:
    | {
        label: string;
        type?: ('reference' | 'custom') | null;
        reference?: (number | null) | Page;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  general?:
    | T
    | {
        siteLogo?: T;
        whiteLogo?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  socialMedia?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        columns?:
          | T
          | {
              textColumn?:
                | T
                | {
                    showLogo?: T;
                    text?: T;
                    id?: T;
                    blockName?: T;
                  };
              menuColumn?:
                | T
                | {
                    title?: T;
                    links?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              contactColumn?:
                | T
                | {
                    title?: T;
                    showAddress?: T;
                    showPhone?: T;
                    showEmail?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        bottomLinks?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        copyright?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu_select".
 */
export interface MainMenuSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        type?: T;
        reference?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}